changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

nmHoistingLimits: workspaces

nmSelfReferences: true

nodeLinker: pnp

packageExtensions:
  "@grpc/grpc-js@*":
    dependencies:
      "@types/long": "*"
  markdownlint-cli@*:
    dependencies:
      deep-extend: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: "https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

pnpMode: strict

yarnPath: .yarn/releases/yarn-3.2.0.cjs
