name: code

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  test:
    name: build, lint, and test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      - name: Using node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install yarn dependencies
        run: yarn install --immutable
      - name: Build package
        run: yarn workspace ${{ inputs.package }} build
      - name: Lint package
        run: yarn workspace ${{ inputs.package }} lint
      - name: Run package unit tests
        run: yarn workspace ${{ inputs.package }} test:unit
  draft-release:
    name: draft release
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Create release draft
        id: release-wizard
        uses: darioblanco/release-wizard@v2.0.3
        with:
          app: ${{ inputs.package }}
          draft: true
          templatePath: release-wizard.md
          token: ${{ secrets.token }}
          withV: false
