name: dotenv-loader-extended

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/dotenv-loader-extended.yaml
      - packages/dotenv-loader-extended/**
      - package.json
      - tsconfig.json
      - types/**/*.ts
      - '!**.md'
      - '!**/.gitignore'
  pull_request:
    paths:
      - .github/workflows/dotenv-loader-extended.yaml
      - packages/dotenv-loader-extended/**
      - package.json
      - tsconfig.json
      - types/**/*.ts
      - '!**.md'
      - '!**/.gitignore'

jobs:
  code:
    uses: ./.github/workflows/code.yaml
    with:
      package: dotenv-loader-extended
    secrets:
      token: ${{ secrets.REPO_ACCESS_TOKEN }}
