name: grpc-boom

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/grpc-boom.yaml
      - packages/grpc-boom/**
      - package.json
      - tsconfig.json
      - types/**/*.ts
      - '!**.md'
      - '!**/.gitignore'
  pull_request:
    paths:
      - .github/workflows/grpc-boom.yaml
      - packages/grpc-boom/**
      - package.json
      - tsconfig.json
      - types/**/*.ts
      - '!**.md'
      - '!**/.gitignore'

jobs:
  code:
    uses: ./.github/workflows/code.yaml
    with:
      package: grpc-boom
    secrets:
      token: ${{ secrets.REPO_ACCESS_TOKEN }}
