name: grpc-ts-health-check

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/grpc-ts-health-check.yaml
      - packages/grpc-ts-health-check/**
      - package.json
      - tsconfig.json
      - types/**/*.ts
      - '!**.md'
      - '!**/.gitignore'
  pull_request:
    paths:
      - .github/workflows/grpc-ts-health-check.yaml
      - packages/grpc-ts-health-check/**
      - package.json
      - tsconfig.json
      - types/**/*.ts
      - '!**.md'
      - '!**/.gitignore'

jobs:
  code:
    uses: ./.github/workflows/code.yaml
    with:
      package: grpc-ts-health-check
    secrets:
      token: ${{ secrets.REPO_ACCESS_TOKEN }}
