name: heart-ping

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/heart-ping.yaml
      - packages/heart-ping/**
      - package.json
      - tsconfig.json
      - types/**/*.ts
      - '!**.md'
      - '!**/.gitignore'
  pull_request:
    paths:
      - .github/workflows/heart-ping.yaml
      - packages/heart-ping/**
      - package.json
      - tsconfig.json
      - types/**/*.ts
      - '!**.md'
      - '!**/.gitignore'

jobs:
  code-workflow:
    uses: ./.github/workflows/code-workflow.yaml
    with:
      package: heart-ping
    secrets:
      token: ${{ secrets.REPO_ACCESS_TOKEN }}
