name: node-ts-uuid

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/node-ts-uuid.yaml
      - packages/node-ts-uuid/**
      - package.json
      - tsconfig.json
      - types/**/*.ts
      - '!**.md'
      - '!**/.gitignore'
  pull_request:
    paths:
      - .github/workflows/node-ts-uuid.yaml
      - packages/node-ts-uuid/**
      - package.json
      - tsconfig.json
      - types/**/*.ts
      - '!**.md'
      - '!**/.gitignore'

jobs:
  code-workflow:
    uses: ./.github/workflows/code-workflow.yaml
    with:
      package: node-ts-uuid
    secrets:
      token: ${{ secrets.REPO_ACCESS_TOKEN }}
