name: publish-nest-typed-config-extended

on:
  push:
    tags:
      - 'nest-typed-config-extended/*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: The version to publish
        required: true

jobs:
  publish:
    uses: ./.github/workflows/publish.yaml
    with:
      directory: packages/nest-typed-config-extended
      package: nest-typed-config-extended
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      npm-publish-token: ${{ secrets.NPM_PUBLISH_TOKEN }}
      token: ${{ secrets.REPO_ACCESS_TOKEN }}
