name: publish-heart-ping

on:
  push:
    tags:
      - 'heart-ping/*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: The version to publish
        required: true

jobs:
  publish:
    uses: ./.github/workflows/publish.yaml
    with:
      directory: packages/heart-ping
      package: heart-ping
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      npm-publish-token: ${{ secrets.NPM_PUBLISH_TOKEN }}
      token: ${{ secrets.REPO_ACCESS_TOKEN }}
