name: publish-grpc-ts-health-check

on:
  push:
    tags:
      - 'grpc-ts-health-check/*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: The version to publish
        required: true

jobs:
  publish:
    uses: ./.github/workflows/publish.yaml
    with:
      directory: packages/grpc-ts-health-check
      package: grpc-ts-health-check
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      npm-publish-token: ${{ secrets.NPM_PUBLISH_TOKEN }}
      token: ${{ secrets.REPO_ACCESS_TOKEN }}
